### ISSUE TITLE
Process input needed fixes

### ISSUE THREAD

**Issue by tmontes** [tmontes/ppytty#110]
Hand tested scenario:
* Two process + their windows.
* `/bin/bash` and `sys.executable` for a Python REPL.

Tested systems:
* macOS Sierra's Terminal, Python 3.6.6, bash 3.2.57.
* raspbian stretch, via ssh from macOS Sierra's terminal, Python 3.6.5, bash 4.4.12.
* Ubuntu 18.04, Gnome Terminal, Python 3.6.5, bash 4.4.19.

Test procedure:
* [x] Try CTRL-C. (fixed in PR #111)
  * Expected behavior: interrupts current line, maybe prints something, new blank prompt below.
* [x] Type spaces and then backspace. (fixed in PR #112)
  * Expected: Cursor moves right as spaces are types and then moves left as they're backspaced.
* [x] Type `word word word word` the edit the line with cursor movement (emacs and vi keybindings). . (fixed in PR #112)
  * Cursor moves as expected.
* [x] Send a SIGINT from the bash window to the Python REPL. (did nothing, suspect fixed from PR #112)
  * Expected: `KeyboardInterrupt` should be displayed. Focus and visible should still be in the bash shell!

Test results matrix:

Test | macOS | raspbian | Ubuntu
---- | ----- | -------- | ------
Python CTRL-C | ok | no effect | no effect
Python Space/Back | space ok, back not ok [1] | ok | ok
bash CTRL-C | ok |  ok, `^C` echoed | ok, `^C` echoed
bash Space/back | ok | ok | ok
Python line edits | no visual cursor moves | no visual cursor moves | no visual cursor moves
bash line edits | no visual cursor moves | no visual cursor moves | no visual cursor moves

[1] Cursor position is actually tracked and the next "visible" input is be properly positioned as well as the cursor, which is also correctly updated.

Interesting... Needs more investigation.

**Comment by tmontes** [comment]
All identified cases fixed on three platforms. Closing.
