### ISSUE TITLE
Add sub-process support

### ISSUE THREAD

**Issue by tmontes** [tmontes/ppytty#5]
General idea:
* [x] Tasks can ask the kernel to spawn an operating system process.
* [x] Kernel will require that process to be associated to a window.
* [x] Such window must be previously created by the task and passed to the "spawn process" trap.
* [x] Kernel will create a PTY and automatically handle all process I/O via the PTY and the Window.
* [x] Keyboard input, from the kernel Terminal, will go to the process if the Window itself "has focus".

More:
* [x] ~~On Task termination (reaching end of run, or stopped by a parent), the kernel will (try hard to) stop the sub-process, destroy the PTY and Window (already accounted for).~~ Decided otherwise: unneeded complexity here + risks of stopping unknown processes. Logging a warning message instead. 
* [x] ~~Task resets need to be considered (the simplest case is: do nothing, sorry!)~~ Makes no sense.
* [x] There should be a kernel trap for the task to "wait" for the spawned process termination (pretty much mimicking the UNIX wait syscall).

More thoughts (copied from later comment to be accounted in issue progress):
* [x] There could be a way of having a task feed data to a process' input, via the PTY. (see #100)
* [x] There could be a way of having a task monitor a process' output, again via the PTY. (see #101)
* [x] Should there be a trap to "destroy" a spawned process? Or should we go for a more low-level (but more controllable) "send signal" trap?

More thoughts (copied from later comment to be accounted in issue progress):
* [x] There could be a way of supporting out of band bidirectional task <-> process communication. (see #102)
   * Needs to be other than stdin/out/err based (given those are handled by the associated terminal).
   * Maybe pipes could be used.
   * Will we need new traps for that or can existing ones be reused, like `message-send` / `message-wait`?

**IMPORTANT**:
* [x] Factor out all real I/O calls (like os.write/read, fcntl.fcntl/ioctl) to the kernel `hw.py` module. (see #103).
  * Needs thinking, otherwise, tests running under the "no i/o" test cases fail to "wake" the select via the "child terminated" pipe write.

**Comment by tmontes** [comment]
More thoughts:
* There could be a way of having a task feed data to a processe's input, via the associated PTY.
* Should there be a trap to "destroy" a spawned process? Or should we go for a more low-level (but more controllable) "send signal" trap?

**Comment by tmontes** [comment]
More thoughts:
* There could be a way of supporting bidirectional ppytty <-> process communication.
* Needs to be other than stdin/out/err based (given those are handled by the associated terminal).
* Maybe pipes could be used.
* Will we need new traps for that or can existing ones be reused, like `message-send` / `message-wait`?

**Comment by tmontes** [comment]
**IMPORTANT**:
* Factor out all real I/O calls (like os.write/read, fcntl.fcntl/ioctl) to the kernel `hw.py` module.

**Comment by tmontes** [comment]
Closing after merging PR #104.

Follow-up issues regarding terminal input:
* Fix low-level I/O loop preventing some input from being forwarded to PTYs (#105).
* Fix cursor visibility across process window focusing  (#106).
* Visually indicate focus changes (#107).
